bot:
 # Publish all joint states -----------------------------------
 joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

 # Position Controllers ---------------------------------------
 joint1_position_controller:
   type: hardware_interface/VelocityJointInterface
   joint: right_left_wheel_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}
